---
title: "training_plotting"
author: "Leah Kemp"
date: "5/4/2021"
output:
  html_document:
    code_download: true
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: true
      smooth_scroll: true
  editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r}
# Load libraries
library(googlesheets4)
library(tidyverse)
library(janitor)
library(ggplot2)
library(DT)

# Load data from google sheets
data_targeting_requirements <- read_sheet("https://docs.google.com/spreadsheets/d/10gONryFN9afkoZvwuJ18rZ_kEO2p_R-H2O85Nr8ktv4/edit#gid=1933731552", sheet = "targeting_the_requirements")

# Format all columns that have a date in their name, to integer format
data_targeting_requirements <- data_targeting_requirements %>%
  mutate_at(vars(matches("\\d+/\\d+/\\d+")), as.integer)

# Remove some columns to only get the sets and reps
data_targeting_requirements_reps_secs <- data_targeting_requirements %>%
  select(-c(`my_rating_7/2/21`)) %>%
  select(!contains(c("notes", "weight")))

# Make this data long
data_targeting_requirements_reps_secs_long <- pivot_longer(data_targeting_requirements_reps_secs,
                       cols= -c(requirement, exercise),
                       names_pattern = "(\\d+/\\d+/\\d+).(....).(reps_or_secs)$",
                       names_to = c("date", "set", "reps_secs")) %>% 
  mutate(date=ifelse(date=="", "value", date))

# Clean up columns
data_targeting_requirements_reps_secs_long <- data_targeting_requirements_reps_secs_long %>%
  select(-reps_secs) %>%
  rename(reps_secs = value)

# Format date column as a date
data_targeting_requirements_reps_secs_long$date <- as.Date(data_targeting_requirements_reps_secs_long$date,"%d/%m/%y")

# Remove rows for which no observation was made for reps_secs (ie. I didn't do the exercise)
data_targeting_requirements_reps_secs_long <- data_targeting_requirements_reps_secs_long %>%
  # recode empty strings "" by NAs
  na_if("") %>%
  # remove NAs
  na.omit
```

### Number of sets

```{r}
data_targeting_requirements_reps_secs_long %>%
  group_by(exercise, requirement) %>%
  summarise(number_of_sets_completed = n()) %>%
  arrange(desc(number_of_sets_completed)) %>%
  datatable(filter = "top",
              rownames = FALSE,
              colnames = c("Exercise",
                           "Requirement",
                           "Number of sets"),
              extensions = list("ColReorder" = NULL,
                                "Buttons" = NULL,
                                "FixedColumns" = list(leftColumns=1)),
              options = list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = list(list(width = "200px", targets = 0)),
                lengthMenu = list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  list("copy",
                       list(extend = "collection",
                            buttons = c("csv", "excel", "pdf"),
                            text = "Download"),
                       I("colvis"))))
```

### Number of sessions

```{r}
data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise) %>%
  summarise(number_of_sessions_exercise_completed = n_distinct(date)) %>%
  arrange(desc(number_of_sessions_exercise_completed)) %>%
  datatable(filter = "top",
              rownames = FALSE,
              colnames = c("Exercise",
                           "Requirement",
                           "Number of sessions"),
              extensions = list("ColReorder" = NULL,
                                "Buttons" = NULL,
                                "FixedColumns" = list(leftColumns=1)),
              options = list(
                dom = "BRrltpi",
                autoWidth = TRUE,
                columnDefs = list(list(width = "200px", targets = 0)),
                lengthMenu = list(c(10, 50, -1), c("10", "50", "All")),
                ColReorder = TRUE,
                buttons =
                  list("copy",
                       list(extend = "collection",
                            buttons = c("csv", "excel", "pdf"),
                            text = "Download"),
                       I("colvis"))))
```

### Anti-extension core strength

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Anti-extension core strength") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        text = element_text(size = 8))
```

### Anti-lateral core strength

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Anti-lateral core strength") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

### Anti-rotation core strength

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Anti-rotation core strength") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

### Hip flexor flexibility

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Hip flexor flexibility") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

### Hip flexor flexibility

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Hip flexor flexibility") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

### Hip flexion strength

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, exercise, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  filter(requirement == "Hip flexion strength") %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(exercise)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

### Summary

```{r}
# Summarise data by date and exercise
time_series_data <- data_targeting_requirements_reps_secs_long %>%
  group_by(requirement, date) %>%
  summarise(number_of_sets_completed = n())

# Plot
time_series_data %>%
  ggplot(aes(x = date, y = number_of_sets_completed)) +
  geom_bar(stat="identity") +
  theme(legend.position = "none") +
  facet_wrap(vars(requirement)) +
  labs(title = "",
       x = "Date",
       y = "Number of sets") +
  theme_bw() +
  theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                   hjust = 0.5, vjust = 0.5),
        axis.text.y = element_text(colour = "grey20", size = 8),
        legend.title = element_blank(),
        text = element_text(size = 8))
```

