---
title: "Training data analysis"
author: "Leah Kemp"
always_allow_html: true
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: false
    self_contained: yes
  editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
# global chunk settings
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, fig.align = "center")
```

```{r}
# install packages
utils::install.packages("googlesheets4")
utils::install.packages("tidyverse")
utils::install.packages("janitor")
utils::install.packages("DT")
utils::install.packages("scales")
utils::install.packages("lubridate")
utils::install.packages("plotly")
utils::install.packages("gtools")
```

```{r}
# load packages
base::library(googlesheets4)
base::library(tidyverse)
base::library(janitor)
base::library(DT)
base::library(scales)
base::library(lubridate)
base::library(plotly)
base::library(gtools)
```

```{r}
# to utilise a github action to automatically render this rmd to htmk and render a github pages webpage
# this code chunk isn't required to render locally

# get the api key for accessing google sheets stored in the secrets section of the github repo
json <- base::Sys.getenv("SHEETS_API_JSON")

# utilise the google sheets api key to autorise access to the google sheets
googlesheets4::gs4_auth_configure(googlesheets4::gs4_auth(email = "leahmhkemp@gmail.com", path=json))
```

```{r}
# web links to excel spreadsheets in google docs
#TP1 <- "https://docs.google.com/spreadsheets/d/10gONryFN9afkoZvwuJ18rZ_kEO2p_R-H2O85Nr8ktv4/edit#gid=0"
#TP2 <- "https://docs.google.com/spreadsheets/d/1jSN7xN3CIQUQNUssWz2c9Wz-ab5qCaBYaYvdsNFKSY0/edit#gid=35820724"
TP3 <- "https://docs.google.com/spreadsheets/d/10_6J7E05NfRtssvikOKT3Fstxxl7lKAO1jbXFPL_DAw/edit#gid=1398744623"

# read in data from google sheets
TP3_M2_GYM_FULL_BODY <- read_sheet(TP3, sheet = "M2_GYM_FULL_BODY")
TP3_M1_GYM_FULL_BODY <- read_sheet(TP3, sheet = "M1_GYM_FULL_BODY")
TP3_M2_POLE_CONDITIONING <- googlesheets4::read_sheet(TP3, sheet = "M2_POLE_CONDITIONING")

#TP2_M5_POLE_CONDITIONING <- read_sheet(TP2, sheet = "M5_POLE_CONDITIONING")
#TP2_M5_GYM_FULL_BODY <- googlesheets4::read_sheet(TP2, sheet = "M5_GYM_FULL_BODY")
#TP2_M5_DAILY_FLEX <- googlesheets4::read_sheet(TP2, sheet = "M5_DAILY_FLEX")
#TP2_M4_POLE_CONDITIONING <- read_sheet(TP2, sheet = "M4_POLE_CONDITIONING")
#TP2_M4_DAILY_FLEX <- googlesheets4::read_sheet(TP2, sheet = "M4_DAILY_FLEX")
#TP2_M4_POLE_OPEN_TRAIN <- googlesheets4::read_sheet(TP2, sheet = "M4_POLE_OPEN_TRAIN")
#TP2_M4_GYM_FULL_BODY <- googlesheets4::read_sheet(TP2, sheet = "M4_GYM_FULL_BODY")
#TP2_M3_DAILY_FLEX <- googlesheets4::read_sheet(TP2, sheet = "M3_DAILY_FLEX")
#TP2_M3_POLE_UPPER_BODY_CORE <- googlesheets4::read_sheet(TP2, sheet = "M3_POLE_UPPER_BODY_CORE")
#TP2_M3_GYM_FULL_BODY <- googlesheets4::read_sheet(TP2, sheet = "M3_GYM_FULL_BODY")
#TP2_M2_FULL_BODY <- googlesheets4::read_sheet(TP2, sheet = "M2_FULL_BODY")
#TP2_M2_CORE_FLEX <- googlesheets4::read_sheet(TP2, sheet = "M2_CORE_FLEX")
#TP2_M1_POLE <- googlesheets4::read_sheet(TP2, sheet = "M1_POLE")
#TP2_M1_GYM <- googlesheets4::read_sheet(TP2, sheet = "M1_GYM")

#TP1_GYM_CORE_FLEX <- googlesheets4::read_sheet(TP1, sheet = "GYM_CORE_FLEX")
#TP1_POLE_CONDITIONING <- googlesheets4::read_sheet(TP1, sheet = "POLE_CONDITIONING")

# create a list of the datasets I'm working with
dataset_list <- base::list(TP3_M2_GYM_FULL_BODY,
                           TP3_M1_GYM_FULL_BODY,
                           TP3_M2_POLE_CONDITIONING)
#TP2_M5_POLE_CONDITIONING,
#TP2_M5_GYM_FULL_BODY,
#TP2_M5_DAILY_FLEX,
#TP2_M4_POLE_CONDITIONING,
#TP2_M4_DAILY_FLEX,
#TP2_M4_POLE_OPEN_TRAIN,
#TP2_M4_GYM_FULL_BODY,
#TP2_M3_DAILY_FLEX,
#TP2_M3_POLE_UPPER_BODY_CORE,
#TP2_M3_GYM_FULL_BODY,
#TP2_M2_FULL_BODY,
#TP2_M2_CORE_FLEX,
#TP2_M1_POLE,
#TP2_M1_GYM,
#TP1_POLE_CONDITIONING,
#TP1_GYM_CORE_FLEX)

# setup my function to prepare the weights data
prepare_weights_data <- function(df_list) {
  
  data <- df_list %>%
    # recode empty strings "" by NAs
    dplyr::na_if("") %>%
    
    # remove empty rows
    janitor::remove_empty(c("rows")) %>%  
    
    # remove some columns to only get the weights data
    # this will also remove columns that don't have a date in the name (data hasn't been entered in those columns)
    dplyr::select(requirement,
                  exercise,
                  matches("\\d{1,2}/\\d{1,2}/\\d{1,4}")) %>%
    dplyr::select(!dplyr::contains(c("notes", "reps_or_secs"))) %>%
    
    # format all columns that have a date in their name, to integer format
    dplyr::mutate_at(dplyr::vars(dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,4}.set")), base::as.double) %>%
    
    # make this data long for downstream analyses
    # this also extracts the date from the column names and makes a variable out of it
    tidyr::pivot_longer(cols = -c(requirement, exercise),
                        names_pattern = "(\\d{1,2}/\\d{1,2}/\\d{1,4}).(....).(weight)$",
                        names_to = c("date", "set", "weight")) %>%
    dplyr::mutate(date=base::ifelse(date=="", "value", date)) %>%
    
    # clean up columns
    dplyr::select(-weight) %>%
    dplyr::rename(weight = value) %>%
    
    # remove rows with NA values (exercise not done)
    stats::na.omit()
  
  # format date column as a date
  data$date <- base::as.Date(data$date,"%d/%m/%y", tz = "NZ")
  
  return(data)
  
}

# setup my function to prepare the reps/secs data
prepare_reps_or_secs_data <- function(df_list) {
  
  data <- df_list %>%
    # recode empty strings "" by NAs
    dplyr::na_if("") %>%
    
    # remove empty rows
    janitor::remove_empty(c("rows")) %>%  
    
    # remove some columns to only get the sets and reps
    # this will also remove columns that don't have a date in the name (data hasn't been entered in those columns)
    dplyr::select(requirement,
                  exercise,
                  dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,4}")) %>%
    # remove some columns to only get the sets and reps
    select(!contains(c("notes", "weight"))) %>%
    
    # format all columns that have a date in their name, to integer format
    dplyr::mutate_at(dplyr::vars(dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,4}.set")), base::as.integer) %>%
    
    # make this data long for downstream analyses
    # this also extracts the date from the column names and makes a variable out of it
    tidyr::pivot_longer(cols = -c(requirement, exercise),
                        names_pattern = "(\\d{1,2}/\\d{1,2}/\\d{1,4}).(....).(reps_or_secs)$",
                        names_to = c("date", "set", "reps_or_secs")) %>%
    dplyr::mutate(date=base::ifelse(date=="", "value", date)) %>%
    
    # clean up columns
    dplyr::select(-reps_or_secs) %>%
    dplyr::rename(reps_or_secs = value) %>%
    
    # remove rows with NA values (exercise not done)
    stats::na.omit()
  
  # format date column as a date
  data$date <- base::as.Date(data$date,"%d/%m/%y", tz = "NZ")
  
  return(data)
  
}

# apply my function to prepare weights and reps/secs data
weights_data <- base::lapply(dataset_list, prepare_weights_data)
reps_or_secs_data <- base::lapply(dataset_list, prepare_reps_or_secs_data)

# collapse dataframes into one dataset
weights_data <- base::Reduce(base::rbind, weights_data)
reps_or_secs_data <- base::Reduce(base::rbind, reps_or_secs_data)

# merge weights and reps/secs data
data <- dplyr::full_join(weights_data,
                         reps_or_secs_data,
                         by = c("requirement", "exercise", "date", "set"))

# replace missing values for weight (where I didn't enter a value since no weight was used) with 0
data <- base::replace(data, base::is.na(data), 0)

# generalise the requirement list
upper_body_strength <- c("Cup grip handspring deadlift",
                         "Internal and external shoulder rotation",
                         "No leg climb",
                         "Pushing strength",
                         "Shoulder flexion (with external rotation)",
                         "Shoulder flexion (with neutral)",
                         "Shoulder mount deadlift",
                         "True grip ayesha",
                         "Twisted grip handspring deadlift",
                         "Upper body power",
                         "Upper body strength",
                         "Pulling strength")

lower_body_strength <- c("Lower body power",
                         "Lower body strength")

core_strength <- c("Anti-extension core strength",
                   "Anti-lateral core strength",
                   "Anti-rotation core strength")

full_body_strength <- c("Full body strength")

upper_body_flexibility <- c("Back flexibility",
                            "Thoracic rotation",
                            "Thoracic lateral bend",
                            "Upper back/shoulder flexibility",
                            "Shoulder flexion flexibility and strength")

lower_body_flexibility <- c("Active hamstring flexibility",
                            "Active hamstring flexibility/hip flexion strength",
                            "Active hip adduction and abduction",
                            "Front splits",
                            "Hamstring nerve tension",
                            "Hip extension flexibility",
                            "Internal and external hip rotation",
                            "Middle split",
                            "Pancake split",
                            "Foot point",
                            "Microbend drills",
                            "Hip flexor flexibility",
                            "Hamstring flexibility",
                            "Hip flexion strength",
                            "Glute and hamstring strength",
                            "Hip abduction strength",
                            "Hip adduction strength",
                            "Hamstring flexibility")

skills <- c("Shouldermount",
            "Shouldermount flag",
            "Shouldermount deadlift",
            "Shouldermount hops up pole",
            "Muscle up to pencil",
            "Human flag",
            "Spatchcock",
            "Twisted grip handspring deadlift",
            "Twisted grip aerial handspring",
            "Twisted grip iron X",
            "Bird of paradise",
            "No leg climb",
            "Twisted grip muscle up to pencil",
            "Invert",
            "Aerial invert")

# add this broader requirements as a new column in my data
data <- data %>%
  dplyr::mutate(requirement_broad = dplyr::case_when(requirement %in% upper_body_strength ~ "Upper body strength",
                                                     requirement %in% lower_body_strength ~ "Lower body strength",
                                                     requirement %in% core_strength ~ "Core strength",
                                                     requirement %in% full_body_strength ~ "Full body strength",
                                                     requirement %in% upper_body_flexibility  ~ "Upper body flexibility",
                                                     requirement %in% lower_body_flexibility ~ "Lower body flexibility",
                                                     requirement %in% skills ~ "Skills"))

# setup plotting functions
time_series_plot <- function(data, wrap_variable) {
  data %>%
    ggplot2::ggplot(aes(x = date, y = number_of_sets_completed)) +
    ggplot2::geom_bar(stat="identity") +
    ggplot2::theme(legend.position = "none") +
    ggplot2::facet_wrap(dplyr::vars(exercise), ncol = 1) +
    ggplot2::geom_vline(xintercept = base::as.numeric("18/12/2021"), colour = "red") +
    ggplot2::labs(title = "",
                  x = "Date",
                  y = "Number of sets") +
    ggplot2::theme_bw() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(colour = "grey20", size = 8, angle = 90,
                                                       hjust = 0.5, vjust = 0.5),
                   axis.text.y = ggplot2::element_text(colour = "grey20", size = 8),
                   legend.title = ggplot2::element_blank(),
                   text = ggplot2::element_text(size = 8)) +
    # create a vertical line in plots at certain date where all my training data was collected (finished up with Jhene)
    ggplot2::scale_x_date(labels = scales::date_format("%Y-%m-%d"),
                          breaks = "1 month", date_labels = base::paste0("%m", "/", "%Y"))
}

time_series_summary_broad_plot <- function(data) {
  data %>%
    ggplot2::ggplot(aes(x = date, y = number_of_sets_completed)) +
    ggplot2::geom_bar(stat="identity") +
    ggplot2::theme(legend.position = "none") +
    ggplot2::facet_wrap(dplyr::vars(requirement_broad), ncol = 1) +
    ggplot2::geom_vline(xintercept = base::as.numeric("18/12/2021"), colour = "red") +
    ggplot2::labs(title = "",
                  x = "Date",
                  y = "Number of sets") +
    ggplot2::theme_bw() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(colour = "grey20", size = 8, angle = 90,
                                                       hjust = 0.5, vjust = 0.5),
                   axis.text.y = ggplot2::element_text(colour = "grey20", size = 8),
                   legend.title = ggplot2::element_blank(),
                   text = ggplot2::element_text(size = 8)) +
    # create a vertical line in plots at certain date where all my training data was collected (finished up with Jhene)
    ggplot2::scale_x_date(labels = scales::date_format("%Y-%m-%d"),
                          breaks = "1 month", date_labels = base::paste0("%m", "/", "%Y"))
}

time_series_summary_plot <- function(data) {
  data %>%
    ggplot2::ggplot(aes(x = date, y = number_of_sets_completed)) +
    ggplot2::geom_bar(stat="identity") +
    ggplot2::theme(legend.position = "none") +
    ggplot2::facet_wrap(dplyr::vars(requirement), ncol = 1) +
    ggplot2::geom_vline(xintercept = base::as.numeric("18/12/2021"), colour = "red") +
    ggplot2::labs(title = "",
                  x = "Date",
                  y = "Number of sets") +
    ggplot2::theme_bw() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(colour = "grey20", size = 8, angle = 90,
                                                       hjust = 0.5, vjust = 0.5),
                   axis.text.y = ggplot2::element_text(colour = "grey20", size = 8),
                   legend.title = ggplot2::element_blank(),
                   text = ggplot2::element_text(size = 8)) +
    # create a vertical line in plots at certain date where all my training data was collected (finished up with Jhene)
    ggplot2::scale_x_date(labels = scales::date_format("%Y-%m-%d"),
                          breaks = "1 month", date_labels = base::paste0("%m", "/", "%Y"))
}
```

## PR

```{r, out.width = "100%"}
# get the combinations of weights and reps/sec for each exercise
weight_reps_pairs <- data %>%
  dplyr::select(-c(set, requirement, requirement_broad)) %>%
  dplyr::group_by(exercise,reps_or_secs, weight) %>%
  dplyr::summarise(reps_or_secs, weight)

# split dataset by exercise
weight_reps_pairs_by_exercise <- base::split(weight_reps_pairs, weight_reps_pairs$exercise)

get_pr <- function(data_list) {
  
  # order data by highest weight and highest number of reps/secs (priority to highest weight)
  ordered <- data_list %>%
    dplyr::arrange(dplyr::desc(weight), dplyr::desc(reps_or_secs))
  
  # get the top row
  pr <- ordered[1, ]
  
  return(pr)
  
}

# apply my function to my list of datasets (so the pr is calculated for each exercise)
pr <- base::lapply(weight_reps_pairs_by_exercise, get_pr)

# collapse results into a single dataframe
pr <- base::Reduce(rbind, pr)

# put in table
pr %>%
  dplyr::select(exercise, reps_or_secs, weight) %>%
  DT::datatable(filter = "top",
                colnames = c("Exercise",
                             "Reps/secs",
                             "Max weight"),
                rownames = FALSE)
```

## Sessions completed

```{r}
# setup my function to prepare the sessions completed data
prepare_session_data <- function(df_list) {
    
  data <- df_list %>%
  # recode empty strings "" by NAs
  dplyr::na_if("") %>%
  
  # remove empty rows
  janitor::remove_empty(c("rows")) %>%  
  
  # remove some columns to only get the sets and reps
  # this will also remove columns that don't have a date in the name (data hasn't been entered in those columns)
  dplyr::select(session,
                dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,4}")) %>%
  # remove some columns to only get the session
  select(!contains(c("notes", "weight"))) %>%
  
  # format all columns that have a date in their name, to integer format
  dplyr::mutate_at(dplyr::vars(dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,4}.set")), base::as.integer) %>%
  
  # make this data long for downstream analyses
  # this also extracts the date from the column names and makes a variable out of it
  tidyr::pivot_longer(cols = -c(session),
                      names_pattern = "(\\d{1,2}/\\d{1,2}/\\d{1,4}).(....).(reps_or_secs)$",
                      names_to = c("date", "set", "reps_or_secs")) %>%
  dplyr::mutate(date=base::ifelse(date=="", "value", date)) %>%
  
  # clean up columns
  dplyr::select(c(session, date)) %>%
  
  # remove rows with NA values (exercise not done)
  stats::na.omit() %>%
  
  # get unique sessions per date
  base::unique()
  
  # format date column as a date
  data$date <- base::as.Date(data$date,"%d/%m/%y", tz = "NZ")
  
  return(data)
}

# apply my function to prepare weights and reps/secs data
session_data <- base::lapply(dataset_list, prepare_session_data)

# collapse dataframes into one dataset
session_data <- base::Reduce(base::rbind, session_data)

# create a column that specifies the week and week
session_data <- session_data %>%
  dplyr::mutate(year_week = paste0(lubridate::year(lubridate::ymd(session_data$date)),
                                   "_",
                                   lubridate::week(lubridate::ymd(session_data$date))))

# remove data previous than Dec 2021 since I was doing personal training sessions where the bulk of my training data wasn't recorded
session_data <- session_data %>%
  dplyr::filter(date > "2021-12-31")

# summarise data by week and exercise
session_data <- session_data %>%
  dplyr::group_by(session, year_week) %>%
  dplyr::summarise(number_of_sessions_completed = base::length(base::unique(date)))

# naturally sort week/year column
session_data$year_week <- gtools::mixedsort(session_data$year_week)
```

*Note. this plot doesn't includes only strength and flexibility conditioning sessions, it excludes pole skills sessions, pole classes and HITT training*

```{r, out.width = "100%"}
plot_ly(data = session_data,
        x = ~year_week,
        y = ~number_of_sessions_completed,
        color = ~session,
        type = "bar") %>%
  plotly::layout(barmode = "stack",
                 xaxis = base::list(title = "Year/week"),
                 yaxis = base::list(title = "Number of sessions completed"))
```

## Sets completed - time series

```{r}
# summarise data by broad requirement and date
time_series_data <- data %>%
  dplyr::group_by(requirement_broad, date) %>%
  dplyr::summarise(number_of_sets_completed = n())

# remove data previous than Dec 2021 since I was doing personal training sessions where the bulk of my training data wasn't recorded
time_series_data <- time_series_data %>%
  dplyr::filter(date > "2021-12-31")
```

### All categories

```{r, out.width = "100%"}
# split data by broad requirement
time_series_data <- time_series_data %>% base::split(time_series_data$requirement_broad)

# plot
plotly::plot_ly(mode = "lines",
                texttemplate="%{label}") %>%
  plotly::add_trace(data = time_series_data$`Upper body strength`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Upper body strength") %>%
  plotly::add_trace(data = time_series_data$`Lower body strength`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Lower body strength") %>%
  plotly::add_trace(data = time_series_data$`Core strength`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Core strength") %>%
  plotly::add_trace(data = time_series_data$`Full body strength`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Full body strength") %>%
  plotly::add_trace(data = time_series_data$`Lower body flexibility`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Lower body flexibility") %>%
  plotly::add_trace(data = time_series_data$`Upper body flexibility`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Upper body flexibility") %>%
  plotly::add_trace(data = time_series_data$`Skills`,
                    x = ~date,
                    y = ~number_of_sets_completed,
                    name = "Skills") %>%
  plotly::layout(showlegend = TRUE,
                 xaxis = base::list(rangeslider = base::list(visible = TRUE),
                                    rangeselector = base::list(
                                      buttons = base::list(
                                        base::list(count=1, label="1m", step="month", stepmode="backward"),
                                        base::list(count=3, label="3m", step="month", stepmode="backward"),
                                        base::list(count=6, label="6m", step="month", stepmode="backward"),
                                        base::list(count=1, label="YTD", step="year", stepmode="todate"),
                                        base::list(count=1, label="1y", step="year", stepmode="backward"),
                                        base::list(step="all"))))) %>%
  plotly::layout(xaxis = base::list(title = "Date"),
                 yaxis = base::list(title = "Number of sets completed"))
```

## Stretching

### Weekly total time stretching

**Target: 5-10 minutes per week per muscle**

```{r, out.width = "100%"}
DAILY_FLEX <- dplyr::full_join(TP2_M3_DAILY_FLEX, TP2_M4_DAILY_FLEX,  by = c("requirement", "exercise"))

# remove microbend drills
DAILY_FLEX <- DAILY_FLEX %>%
  dplyr::filter(requirement != "Microbend drills")

# recode empty strings "" by NAs
DAILY_FLEX <- DAILY_FLEX %>%
  dplyr::na_if("") 

# format all columns that have a date in their name, to integer format
DAILY_FLEX <- DAILY_FLEX %>%
  dplyr::mutate_at(dplyr::vars(dplyr::matches("\\d{1,2}/\\d{1,2}/\\d{1,2}.set")), base::as.integer)

# remove some columns to only get the sets and reps
# this'll also remove columns that don't have a date in the name (data hasn't been entered in those columns)
DAILY_FLEX <- DAILY_FLEX %>%
  dplyr::select(requirement,
                exercise,
                matches("\\d{1,2}/\\d{1,2}/\\d{1,2}"))

# make this data long for downstream analyses
# this also extracts the date from the column names and makes a variable out of it
DAILY_FLEX_long <- tidyr::pivot_longer(DAILY_FLEX,
                                       cols = -c(requirement, exercise),
                                       names_pattern = "(\\d{1,2}/\\d{1,2}/\\d{1,2}).(....).(reps_or_secs)$",
                                       names_to = c("date", "set", "reps_or_secs")) %>% 
  dplyr::mutate(date=base::ifelse(date=="", "value", date))

# clean up columns
DAILY_FLEX_long <- DAILY_FLEX_long %>%
  dplyr::select(-reps_or_secs) %>%
  dplyr::rename(reps_or_secs = value)

# remove rows with NA values (exercise not done)
DAILY_FLEX_long <- DAILY_FLEX_long %>%
  stats::na.omit()

# format date column as a date
DAILY_FLEX_long$date <- base::as.Date(DAILY_FLEX_long$date,"%d/%m/%y")

# create a column that specifies the week
DAILY_FLEX_long <- DAILY_FLEX_long %>%
  dplyr::mutate(week = lubridate::week(lubridate::ymd(DAILY_FLEX_long$date)))
```

```{r}
# summarise data by week and exercise
time_series_data <- DAILY_FLEX_long %>%
  dplyr::group_by(requirement, exercise, week) %>%
  dplyr::summarise(number_of_reps_or_secs_completed = sum(reps_or_secs))
```

```{r, out.width = "100%"}
# a function for getting integer y-axis values
# (grabbed code from: https://joshuacook.netlify.app/post/integer-values-ggplot-axis/)
integer_breaks <- function(n = 5, ...) {
  fxn <- function(x) {
    breaks <- floor(pretty(x, n, ...))
    names(breaks) <- attr(breaks, "labels")
    breaks
  }
  return(fxn)
}

time_series_data %>%
  ggplot2::ggplot(aes(x = week, y = number_of_reps_or_secs_completed)) +
  ggplot2::geom_bar(stat="identity") +
  ggplot2::theme(legend.position = "none") +
  ggplot2::facet_wrap(dplyr::vars(requirement)) +
  ggplot2::labs(title = "",
                x = "Week",
                y = "Total seconds") +
  ggplot2::theme_bw() +
  ggplot2::theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                            hjust = 0.5, vjust = 0.5),
                 axis.text.y = element_text(colour = "grey20", size = 8),
                 legend.title = element_blank(),
                 text = element_text(size = 8)) +
  ggplot2::geom_hline(yintercept = 300, colour = "orange") +
  ggplot2::geom_hline(yintercept = 600, colour = "forest green") +
  ggplot2::scale_x_continuous(breaks = integer_breaks())
```

### Stretching frequency

**Target: 5-6 days week per week**

```{r}
# summarise data by week and exercise
time_series_data <- DAILY_FLEX_long %>%
  dplyr::group_by(requirement, week) %>%
  dplyr::summarise(number_of_sessions_completed = base::length(base::unique(date)))
```

```{r, out.width = "100%"}
time_series_data %>%
  ggplot2::ggplot(aes(x = week, y = number_of_sessions_completed)) +
  ggplot2::geom_bar(stat="identity") +
  ggplot2::theme(legend.position = "none") +
  ggplot2::facet_wrap(dplyr::vars(requirement)) +
  ggplot2::labs(title = "",
                x = "Week",
                y = "Total number of sessions") +
  ggplot2::theme_bw() +
  ggplot2::theme(axis.text.x = element_text(colour = "grey20", size = 8, angle = 90,
                                            hjust = 0.5, vjust = 0.5),
                 axis.text.y = element_text(colour = "grey20", size = 8),
                 legend.title = element_blank(),
                 text = element_text(size = 8)) +
  ggplot2::geom_hline(yintercept = 5, colour = "orange") +
  ggplot2::geom_hline(yintercept = 6, colour = "forest green") +
  ggplot2::scale_x_continuous(breaks = integer_breaks())
```

## Excercise list

```{r, out.width = "100%"}
# create table of list of exercises
data %>%
  dplyr::select(exercise,
                requirement_broad) %>%
  base::unique() %>%
  # order alphabetically by requirement
  dplyr::arrange(exercise) %>%
  # make factors for table formatting
  dplyr::mutate(requirement_broad = base::as.factor(requirement_broad)) %>%
  DT::datatable(filter = "top",
                colnames = c("Exercise",
                             "Requirement - broad"),
                rownames = FALSE)
```

```{r, cleanup, results = "hide"}
# clean up
rm(list = ls())
```
