seconds:
- "True grip extended butterfly hold"
- "Hamstring strap PNF stretch"
- "Deep lunge back knee on block, foot on wall"
- "Puppy pose on pole/wall"
- "Pole invert finishing position isometric hold"
- "I stepped in gum"
- "Front oversplit"
- "Pancake split"
- "Pancake oversplit"
- "Cobra through full range"
- "Camel pose"
- "Seated twist"
- "Pancake thoracic rotation"
- "Cobra twist"
- "Square front split"
- "Middle split"
- "Deep lunge PNF stretch"
- "Deep lunge foot to butt PNF stretch on block"
- "Pigeon pose foot to butt PNF stretch"
- "Front oversplit PNF lifts"
- "Frog pose PNF series"
- "Passive front oversplit"
- "Frog pose oversplit PNF stretch"
- "Middle split PNF stretch"
- "Passive middle split stretch"
- "Pancake oversplit PNF stretch"
- "Passive pancake stretch"
- "Puppy pose PNF stretch on pole/wall"
- "Weighted PNF upper back stretch on foam roller"
- "Passive weighted upper back stretch on foam roller"
- "Cobra PNF stretch (band resisted)"
- "Passive cobra stretch"
- "Passive floor superman PNF twist (elbow grip)"
- "Passive cobra twist"
- "Pancake lateral bend PNF stretch holding pole"
- "Passive pancake lateral bend stretch"
- "Passive foot point stretch"
- "Twisted grip matrix isometric hold"
- "Inevitable decline"
- "Puppy pose stretch on pole/wall"
- "Passive backbend over elevated foam roller"
- "Passive laying twist"
- "Laying banded middle split PNF stretch"
- "True grip ayesha static hold"
- "Elbow puppy pose stretch"
- "Pec stretch in doorway"
- "Passive standing pole backbend"
- "Passive seated twist"
- "Pole lateral bend stretch"
- "Hamstring bench PNF stretch"
- "Passive hamstring stretch"
- "Deep lunge knee on block passive stretch"
- "Deep lunge PNF knee lifts on block"
- "Front oversplit PNF stretch"
- "Passive front split"
- "Laying weighted and banded passive middle split stretch"
- "Laying weighted and banded middle split PNF stretch"
- "Wide squat"
- "Pancake PNF stretch"
- "Weighted happy baby stretch"
- "Passive pancake oversplit stretch"
- "Standing hamstring PNF series with block"
- "Side lunges no hands"
- "Banded pancake no hands lift up"
- "Banded pancake"
- "Regular lunge"
- "Front oversplit (lay on floor next to leg)"
- "Front oversplit (oversplit back leg)"
- "Lay on back with feet tucked beside butt"
- "Crouched, one straight leg out behind, lift straight leg off floor"
- "Hollow body holds"
- "Contortion handstand"
- "Kneeling back bend"
- "Standing backbend wall reach"
- "Janeiro side bend"
- "Puppy pose on foam roller, roll over shoulders"
- "Bridge"
- "Needlescale with band"
- "Pec stretch on wall"
- "Pole invert starting position isometric hold"
- "Shouldermount finishing position isometric hold"
- "Laying on back, hold swiss ball against wall with feet, single leg lowers"
- "Thoracic rotation in pancake"
reps:
- "Hip abduction machine"
- "Hip adduction machine"
- "Hanging leg raises (tucked knees)"
- "Hanging leg raises (straight legs)"
- "Kneeling cable crunch"
- "Reverse cruches"
- "Laying leg lowers"
- "Standing side bends"
- "Side v up (single leg)"
- "Side v up (double leg)"
- "Cable pallof rotation"
- "Renegade row"
- "Weighted pull overs"
- "Pole invert knee tucks (double arm)"
- "Twisted grip matrix lifts"
- "Pole pull-ups (bent knees - feet on ground)"
- "Cup grip matrix lifts"
- "Pole pull-ups (straight legs - feet on ground)"
- "Seated pike to straddle leg lifts"
- "Seated single leg pike leg lifts (foot pointed up - back against wall)"
- "Front split sliders"
- "Candle stick lowers (double leg)"
- "Candle stick lowers (single leg)"
- "Pole invert pikes (double arm)"
- "Cupid side bends on pole (hands behind head)"
- "Cupid back bends on pole (hands behind head)"
- "Cupid front bends on pole (hands behind head)"
- "Forearm plank with reach"
- "Passive floor superman twist (regular grip)"
- "Passive floor superman twist (elbow grip)"
- "Overhead arm lifts with external rotation"
- "Banded internal shoulder rotation"
- "Banded external shoulder rotation"
- "Internal shoulder rotation isometric press into blocks + external rotation lift offs"
- "Hamstring nerve flossing"
- "Banded hip abduction"
- "Banded hip adduction"
- "Straight leg firehydrants (leg behind, to leg to side)"
- "Middle split sliders"
- "Internal rotation 90-90 back leg hold and release"
- "External rotation 90-90 back leg hold and release"
- "Push-ups (narrow)"
- "One arm downward dog (with torso twist)"
- "L handstand push-ups"
- "Narrow to wide press up jump"
- "Squat jump with air straddle"
- "Seated pike leg lifts with back against wall (feet straight)"
- "Seated pike leg lifts with back against wall (feet turned out)"
- "Elevated straddle roll downs"
- "Elevated candle stick lowers (double leg)"
- "Pike ups"
- "Side bends on back extension machine (hands overhead)"
- "Hanging leg raises with twist (tucked knees)"
- "Dumbbell overhead press"
- "Elevated push-ups (wide)"
- "Rear deltoid machine"
- "Pull-ups (wide - overhand grip)"
- "Pull-ups (narrow - neutral grip)"
- "Hanging scapular retractions"
- "Lat pulldown machine"
- "Seated cable low row"
- "Pec fly machine"
- "Bent over dumbbell fly (bent elbow)"
- "Dumbbell progress rows"
- "Plate loaded high row"
- "Dumbbell shrug"
- "Banded bicep curls"
- "Barbell squat"
- "Glute drive machine"
- "Incline plate loaded leg press"
- "Leg extension machine"
- "Hamstring curl machine"
- "Back extension machine (shrimp)"
- "Short walking lunge"
- "Stationary lunge"
- "Jumping squat"
- "Calf raises"
- "Pistol squats"
- "Straddle ups"
- "Forearm side plank crunches"
- "Forearm side plank leg raise"
- "Reverse crunch with twist"
- "Deep lunge knee lifts off floor"
- "Over the moons with band/stick"
- "Around the worlds with band/stick"
- "Seated pike leg lifts (double leg)"
- "Pancake body lifts (arms overhead)"
- "Seated pancake leg lifts"
- "90/90 series"
- "Cupid side bends on pole (hands overhead)"
- "Plank shoulder taps"
- "Kneeling backbend pulses"
- "Banded seated leg straightens (block under knee)"
- "Seated leg straightens (block under knee)"
- "Twisted grip band assisted deadlift"
- "Pole pull-up negatives (straight legs - feet off ground)"
- "Kneeling banded cervical retraction"
- "Push-ups (wide)"
- "Plough pike roll downs"
- "Twisted grip banded iron X lift"
- "Kneeling thoracic rotation"
- "Dumbbell chest press (incline)"
- "Dumbbell chest press (flat)"
- "Barbell chest press (flat)"
- "Elevated lunge"
- "Hanging leg raises (toes to bar)"
- "Suitcase carries"
- "Pole straddle inverts (straight legs)"
- "Fankick with pull-up"
- "Pole invert knee tuck, pike, straddle (double arm), pull-up, seat (repeat other side)"
- "No leg climb negative"
- "Band assisted shouldermount flag"
- "Bird of paradise"
- "Bent over dumbbell fly (straight arm)"
- "Dumbbell overhead shrug"
- "Bench kneeling dumbbell row"
- "Converging shoulder press machine"
- "Seated low row machine"
- "Standing cable low row"
- "Decline plate loaded chest press"
- "Tricep dip machine"
- "Incline plate loaded leg press (single leg)"
- "Glute drive machine (single leg)"
- "Leg press machine (single leg - side lying)"
- "Walking lunge"
- "Hack squat"
- "Banded jumping squat"
- "Seated banded clams"
- "Step up to overhead press"
- "Hover to leg tap"
- "Captain's chair (straight legs)"
- "Hanging L sit legs side to side"
- "Pole invert knee tuck, pike, pull-up, seat (double arm)"
- "No leg climb"
- "Serial pole straddle inverts (straight legs, no body grip)"
- "Serial pole straddle inverts (straight legs, with body grip)"
- "Pole straddle invert (straight legs), outside leg hang, pullup (repeat other side)"
- "True grip D leg slides (inverted)"
- "Band assisted twisted grip muscle up to pencil"
- "Spatchcock entry"
- "Standing cable rotation row"
- "Incline dumbbell shoulder press"
- "Pull-ups (narrow - overhand grip)"
- "Reverse dumbbell lunge (with knee drive)"
- "Kettlebell side lunge"
- "Landmine press (with knee drive)"
- "Plank pull (on swiss ball)"
- "Barbell deadlift (conventional)"
- "Cable pallof press"
- "Grip strength device"
- "Reverse kettlebell lunge (with knee drive)"
- "Kettlebell side lunge (to floor)"
- "Barbell military press"
- "Incline barbell shoulder press"
- "Cable face pull"
- "Barbell reverse lunge to step up"
- "Kickstand barbell deadlift"
- "Barbell clean"
- "Decline bench partner medicine ball throws with twist"
- "Chin-ups"
- "Barbell push press"
- "Bulgarian lunge"
- "Bullet barbell deadlift"
- "Kettlebell clean and jerk"
- "Hanging wipers"
- "Serial iron X to ayesha"
- "Banded twisted grip deadlift from floor"
- "Twisted grip deadlift from floor"
- "Twisted grip pike muscle up from floor"
- "Banded pike reverse spin"
- "Pike reverse spin"
- "Reverse pole handstand pike deadlifts"
- "Caterpillar climb (hands on floor)"
- "Caterpillar climb (single arm push)"
- "Invert swaps"
- "Seated straddle leg lifts"
- "Standing leg lift series (front, side and back)"
- "Straight leg firehydrants (leg to side)"
- "Pancake split series"
- "Side lunges no hands"
- "Deep lunge knee lifts off floor, with 10 sec hold at end"
- "Knee, knee, pike, straddle up series"
- "Pikes on stability ball"
- "Oblique knee tucks on stability ball"
- "Plank to elbow plank (feet on stability ball)"
- "Spidermans"
- "Elbow plank raises with Swiss ball between feet"
- "Plank, raise opposing arm/leg"
- "Shouldermount lifts into starting position"
- "Laying on back, hold swiss ball against wall with feet, single leg lowers"
