# This is a basic workflow to help you get started with Actions

name: Render R Markdown file as HTML

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
        image: rocker/verse
    env:
      SHEETS_API_KEY: ${{ secrets.SHEETS_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("training_data_analysis.Rmd", output_format = "html_document")'
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: html output
          path: training_data_analysis.html
